server:
   port: 8081

app:
   allowed-db-hosts:
   - localhost
   - 127.0.0.1

spring:
   datasource:
      url: jdbc:postgresql://postgres:5432/Test
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver

   jpa:
      hibernate:
         ddl-auto: update # none | validate | update | create | create-drop
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: TRACE
        